name: "Build documentation"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2

      - name: "Install Python dependencies"
        run: |
          cd doc/
          pip3 install setuptools
          pip3 install -r requirements.txt

      - name: "Build Sphinx Doc"
        run: |
          cd doc/
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/_build/html/
